# Generated by Django 4.2.4 on 2023-08-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_note_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(blank=True, to="api.tag"),
        ),
    ]
